sudo: true
dist: trusty
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "nover" --password-stdin
    - docker build -t node-k8s-tester .
    - docker images
    - REV_COUNT=`git rev-list HEAD --count` 
    - docker tag node-k8s-tester nover/node-k8s-tester:${REV_COUNT}
    - docker tag node-k8s-tester nover/node-k8s-tester:latest
    - docker push nover/node-k8s-tester:${REV_COUNT}
    - docker push nover/node-k8s-tester:latest
env:
  secure: HajsNyRthDp/cFVH+gH3f1d0nHFg+gv3lsWuNtJFtH/vn3Q6muBvf1skbPQ6CoyZ96csMQGhio995lEBzyrT63dY3W18O6+c/qGTA5G2qis0OH0cnf45X+3JdrUaGCMJaS9b3MwLqcsuGJpwZaumvzcSAnwc8CVYVe3u2rpsSVa8JcATFF43VVySdiX+jj+V6JtqME+rYviDPTsiOR9wShlphvvcPm4MN/PA9wmyTqg6VELm8xIiz9x4YfbzT49ev2Icoqp/ITBNNwLZIYO/5rSTWAC9UyQsbcSThxDxha06Y+I4ottrbLNYgV9jx1DTx8OlCp4HDN10TZ/eW0fBhqrRC5GZ7owNxxtjonwH8vEZhDd28ZSEXT21anBsQfxQvLD9CDy/rSbahP90pQsmMXC9EleEiW9i+t22SUDBOjJfqVDHUa7SzPFkaIWVpw5j4CYBkrDOHVT+uw7SfApwD/iKnI0a8zGkbJ1ajRHXGMiD6XNFpgZmEzryO7xvaGGn5c3dhG+h+4JaxADuQf4vkXLULVtDWYrkRfUWxzVXv2COoBw6Fgv0WdZySUl9EfyGfb0VByTKpS4fv8aMFqi+DQeXCaks/8htv0Tlm12L8mQhkzSWiHR+PXIx4WPWr8vQmcLrHE/D+j43cPOGc1rImICAzUHIi69YyHYCJOcsYM0=
