version: '3'
services: 
  redis:
    image: 'redis:3.2-alpine'
    ports:
      - 6379:6379
  rabbit:
    image: 'rabbitmq:3.7-management'
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_PASS=1234rabbitpass
      - RABBITMQ_DEFAULT_USER=rabbit


# $ docker run -d --hostname my-rabbit --name some-rabbit -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password rabbitmq:3-management
